apiVersion: apps/v1
kind: Deployment
metadata:
  name: "cart"
  namespace: ms
  labels:
    app: "cart"
spec:
  selector:
    matchLabels:
      app: "cart"
  replicas: 1
  template:
    metadata:
      labels:
        app: "cart"
    spec:
      containers:
      - name: "cart"
        image: malekjellali1/cart:latest
        resources:
        ports:
        - containerPort: 1004
          name: "cart"
