apiVersion: apps/v1
kind: Deployment
metadata:
  name: "offer"
  namespace: ms
  labels:
    app: "offer"
spec:
  selector:
    matchLabels:
      app: "offer"
  replicas: 1
  template:
    metadata:
      labels:
        app: "offer"
    spec:
      containers:
      - name: "offer"
        image: malekjellali1/offer:latest
        resources:
        ports:
        - containerPort: 1001
          name: "offer"
